language: objective-c
osx_image: xcode7.2
sudo: false

script:
- xcodebuild test -project ByteBackpacker.xcodeproj -scheme "ByteBackpacker iOS" -destination "platform=iOS Simulator,name=iPhone 6" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
- xcodebuild test -project ByteBackpacker.xcodeproj -scheme "ByteBackpacker OS X" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
- bash <(curl -s https://codecov.io/bash) 