branches:
  only:
  - master

language: objective-c
osx_image: xcode8.3

script:
- xcodebuild -project ByteBackpacker.xcodeproj -scheme "ByteBackpacker OS X" build test 
- xcodebuild -project ByteBackpacker.xcodeproj -scheme "ByteBackpacker iOS" -destination "platform=iOS Simulator,name=iPhone 7" build test

after_success:
- bash <(curl -s https://codecov.io/bash)  -J 'ByteBackpacker'
